name: Sync Repository A

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Sync with repository A
        uses: repo-sync/github-sync@v2
        with:
          source_repo: 'HyuDeQueue/DAS-Backend'
          source_branch: 'main'
          destination_branch: 'main'
          github_token: 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
